# Generated by Django 5.0.6 on 2024-06-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Райан Гослинг', max_length=255)),
                ('photo', models.ImageField(default='https://img.redbull.com/images/q_auto,f_auto/redbullcom/2016/05/20/1331795954995_2/%D1%80%D0%B0%D0%B9%D0%B0%D0%BD-%D0%B3%D0%BE%D1%81%D0%BB%D0%B8%D0%BD%D0%B3.jpg', upload_to='classmate_photos/')),
                ('email', models.EmailField(default='goslya@mail.com', max_length=254)),
                ('phone', models.CharField(default='+7777777777', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Экономика', max_length=255)),
                ('link', models.URLField(blank=True, default='https://perm.hse.ru/ba/economics/', null=True)),
                ('what_you_will_study', models.TextField(default='Экономику')),
                ('what_you_will_learn', models.TextField(default='Экономить')),
                ('program_benefits', models.TextField(default='Научился экономить')),
                ('future_prospects', models.TextField(default='Много сэкономишь')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('nav_display', models.BooleanField(default=True)),
                ('nav_position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Тутынина Ольга Владимировна', max_length=255)),
                ('photo', models.ImageField(default='https://perm.hse.ru/pubs/share/thumb/905202217:c190x190+0+0:r190x190!', upload_to='staff_photos/')),
                ('email', models.EmailField(default='oshibanova@hse.ru', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Бартель Андрей Александрович', max_length=255)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('email', models.EmailField(default='aabartel@edu.hse.ru', max_length=254)),
                ('phone', models.CharField(default='+7992*****98', max_length=20)),
                ('resume', models.TextField(default='Ну я')),
            ],
        ),
    ]
