# Generated by Django 5.0.6 on 2024-06-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_leap', models.BooleanField()),
                ('century', models.CharField(max_length=20)),
                ('era', models.CharField(default='н. э.', max_length=10)),
            ],
        ),
    ]
